sudo: false

language: d

d:
  - dmd-2.068.0

install:
  - wget -O doveralls https://github.com/ColdenCullen/doveralls/releases/download/v1.1.4/doveralls_linux_travis
  - chmod +x doveralls
script:
  - dub test -b unittest-cov --compiler=${DC}
  - ./doveralls
