sudo: false

language: d

d:
  - dmd-2.068.0
  - dmd-2.069.1
  - dmd-2.070.2

install:
  - wget -O doveralls https://github.com/ColdenCullen/doveralls/releases/download/v1.2.0/doveralls_linux_travis
  - chmod +x doveralls
script:
  - dub test -b unittest-cov --compiler=${DC}
  - ./doveralls
